build:
  image: golang:1.5
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-codedeploy
    when:
      branch: master

plugin:
  name: CodeDeploy
  desc: Deploys or updates a project on CodeDeploy
  type: deploy
  image: plugins/drone-codedeploy
  labels:
    - aws
    - codedeploy
