[[constraint]]
  name = "github.com/drone/drone-go"
  revision = "eaa41f7836a191224ec5702d2458db07882ec269"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.14"

[prune]
  go-tests = true
  unused-packages = true
